committing changes in /etc after yum run
Package changes:

diff --git a/rc.d/init.d/cgconfig b/rc.d/init.d/cgconfig
--- a/rc.d/init.d/cgconfig
+++ b/rc.d/init.d/cgconfig
@@ -23,23 +23,18 @@
 # Provides:             cgconfig
 # Required-Start:
 # Required-Stop:
-# Should-Start:
-# Should-Stop:
-# Short-Description:    start and stop the WLM configuration
-# Description:          This script allows us to create a default configuration
+# Should-Start:         ypbind
+# Should-Stop:          ypbind
+# Short-Description:    Create and setup control group filesystem(s)
+# Description:          Create and setup control group filesystem(s)
 ### END INIT INFO
 
 # get correct location of binaries from configure
 prefix=/usr;exec_prefix=/usr;sbindir=/sbin
 CGCONFIGPARSER_BIN=$sbindir/cgconfigparser
-CGROUP_FS=cgroup
 CONFIG_FILE=/etc/cgconfig.conf
-
-# support multiple mount points
-declare -a MOUNTPOINT
-declare -a MOUNTOPTS
-maxindex=0
 servicename=cgconfig
+lockfile=/var/lock/subsys/$servicename
 
 #
 # Source LSB routines
@@ -61,17 +56,13 @@ if [ -e /etc/sysconfig/cgconfig ]; then
         . /etc/sysconfig/cgconfig
 fi
 
-RETVAL=0
-
 create_default_groups() {
-        declare defaultcgroup
+	defaultcgroup=
 
-        if [ -f /etc/cgrules.conf ]
-        then
-            read user ctrl defaultcgroup <<< \
-		`grep -m1 '^\*[[:space:]]\+' /etc/cgrules.conf`
-            if [[ -n $defaultcgroup && $defaultcgroup = "*" ]]
-            then
+        if [ -f /etc/cgrules.conf ]; then
+	    read user ctrl defaultcgroup <<< \
+		    $(grep -m1 '^\*[[:space:]]\+' /etc/cgrules.conf)
+            if [ -n "$defaultcgroup" -a "$defaultcgroup" = "*" ]; then
                 log_warning_msg "/etc/cgrules.conf incorrect"
                 log_warning_msg "Overriding it"
                 defaultcgroup=
@@ -115,38 +106,33 @@ create_default_groups() {
 
 start() {
         echo -n "Starting cgconfig service: "
-	if [ -f /var/lock/subsys/$servicename ]
-        then
+	if [ -f "$lockfile" ]; then
             log_warning_msg "lock file already exists"
             return 0
         fi
 
-        if [ $? -eq 0 ]
-        then
-                if [ ! -s $CONFIG_FILE ]
-                then
+        if [ $? -eq 0 ]; then
+                if [ ! -s $CONFIG_FILE ]; then
                     log_failure_msg $CONFIG_FILE "is not configured"
                     return 6
                 fi
 
                 $CGCONFIGPARSER_BIN -l $CONFIG_FILE
                 retval=$?
-                if [ $retval -ne 0 ]
-                then
+                if [ $retval -ne 0 ]; then
                     log_failure_msg "Failed to parse " $CONFIG_FILE
                     return 1
                 fi
         fi
 
-        if [ $CREATE_DEFAULT == "yes" ]; then
+        if [ $CREATE_DEFAULT = "yes" ]; then
                 create_default_groups
         fi
 
-        touch /var/lock/subsys/$servicename
+        touch "$lockfile"
         retval=$?
-        if [ $retval -ne 0 ]
-        then
-            log_failure_msg "Failed to touch " /var/lock/subsys/$servicename
+        if [ $retval -ne 0 ]; then
+            log_failure_msg "Failed to touch $lockfile"
             return 1
         fi
         log_success_msg
@@ -156,7 +142,7 @@ start() {
 stop() {
     echo -n "Stopping cgconfig service: "
     cgclear
-    rm -f /var/lock/subsys/$servicename
+    rm -f "$lockfile"
     log_success_msg
     return 0
 }
@@ -183,38 +169,37 @@ common() {
     trap "trapped INT"   INT
 }
 
+restart() {
+	common
+	stop
+	start
+}
+
+RETVAL=0
+
 case $1 in
     'stop')
         common
-        stop;
+        stop
         RETVAL=$?
         ;;
     'start')
         common
-        start;
-        RETVAL=$?
-        ;;
-    'restart')
-        common
-	stop
         start
         RETVAL=$?
         ;;
-    'reload')
-        common
-	stop
-        start
+    'restart'|'reload')
+	restart
         RETVAL=$?
         ;;
     'condrestart')
-        if [ -f /var/lock/subsys/$servicename ] ; then
-            stop
-            start
+        if [ -f "$lockfile" ]; then
+            restart
             RETVAL=$?
         fi
         ;;
     'status')
-        if [ -f /var/lock/subsys/$servicename ] ; then
+        if [ -f "$lockfile" ]; then
             echo "Running"
             exit 0
         else
diff --git a/rc.d/init.d/kdump b/rc.d/init.d/kdump
--- a/rc.d/init.d/kdump
+++ b/rc.d/init.d/kdump
@@ -43,6 +43,29 @@ if [ -f /etc/sysconfig/kdump ]; then
 	. /etc/sysconfig/kdump
 fi
 
+function single_instance_lock()
+{
+	exec 9>/var/lock/kdump
+	flock 9
+}
+
+# remove_cmdline_param <kernel cmdline> <param1> [<param2>] ... [<paramN>]
+# Remove a list of kernel parameters from a given kernel cmdline and print the result.
+# For each "arg" in the removing params list, "arg" and "arg=xxx" will be removed if exists.
+function remove_cmdline_param()
+{
+	local cmdline=$1
+	shift
+
+	for arg in $@; do
+		cmdline=`echo $cmdline | \
+			 sed -e "s/\b$arg=[^ ]*\b//g" \
+			     -e "s/\b$arg\b//g"`
+	done
+	echo $cmdline
+}
+
+
 function in_xen_pv_guest()
 {
 	grep -q 'xen-percpu-virq  *timer0' /proc/interrupts
@@ -62,17 +85,43 @@ function check_xen_hvm_nopv_premkdumprd()
 	fi
 }
 
+function save_kernel_logs()
+{
+	local _path=$1
+
+	mkdir -p $_path
+
+	if [ ! -f /sbin/vmcore-dmesg ];then
+		$LOGGER "Skipping saving vmcore-dmesg.txt. File /sbin/vmcore-dmesg is not present"
+		return;
+	fi
+
+	echo "kdump: saving vmcore-dmesg.txt to $_path"
+	$LOGGER "saving vmcore-dmesg.txt to $_path"
+	/sbin/vmcore-dmesg /proc/vmcore > $_path/vmcore-dmesg-incomplete.txt
+	if [ $? == 0 ]; then
+		mv $_path/vmcore-dmesg-incomplete.txt $_path/vmcore-dmesg.txt
+		echo "kdump: saved vmcore-dmesg.txt to $_path"
+		$LOGGER "saved vmcore-dmesg.txt to $_path"
+	else
+		echo "kdump: failed to save vmcore-dmesg.txt to $_path"
+		$LOGGER "failed to save vmcore-dmesg.txt to $_path"
+	fi
+
+}
+
 function save_core()
 {
 	local kdump_path
 	kdump_path=`grep ^path $KDUMP_CONFIG_FILE | cut -d' '  -f2-`
 	if [ -z "$kdump_path" ]; then
-		coredir="/var/crash/`date +"%Y-%m-%d-%H:%M"`"
+		coredir="/var/crash/127.0.0.1-`date +"%Y-%m-%d-%H:%M"`"
 	else
-		coredir="${kdump_path}/`date +"%Y-%m-%d-%H:%M"`"
+		coredir="${kdump_path}/127.0.0.1-`date +"%Y-%m-%d-%H:%M"`"
 	fi
 
 	mkdir -p $coredir
+	save_kernel_logs "${coredir}"
 	/usr/sbin/makedumpfile -c --message-level 1 -d 31 /proc/vmcore $coredir/vmcore-incomplete
 	if [ $? == 0 ]; then
 		mv $coredir/vmcore-incomplete $coredir/vmcore
@@ -342,13 +391,11 @@ function load_kdump()
 		min=${min%%.*}
 		if [ "$maj" = "2.6.32" ] && [ $min -lt 171 ]
 		then
-			echo -n "Your kernel is old, please use maxcpus=1 instead of nr_cpus=1"
-			warning
-			echo
+			echo "Your kernel is old, please use maxcpus=1 instead of nr_cpus=1"
+			return 1
 		fi
 	fi
-	KDUMP_COMMANDLINE=`echo $KDUMP_COMMANDLINE | sed -e 's/crashkernel=[^ ]*//'`
-	KDUMP_COMMANDLINE=`echo $KDUMP_COMMANDLINE | sed -e 's/mem=[0-9]\+[GMKgmk]* *//'`
+	KDUMP_COMMANDLINE=`remove_cmdline_param "$KDUMP_COMMANDLINE" crashkernel mem hugepages hugepagesz`
 	KDUMP_COMMANDLINE="${KDUMP_COMMANDLINE} ${KDUMP_COMMANDLINE_APPEND}"
 	avoid_cdrom_drive
 	KDUMP_COMMANDLINE="${KDUMP_COMMANDLINE} ${KDUMP_IDE_NOPROBE_COMMANDLINE}"
@@ -375,16 +422,6 @@ function load_kdump()
 
 function propagate_ssh_key()
 {
-	#Check if selinux is on... must flip to permissive mode
-	#for the moment to create key, then flip back...
-	sedir=`grep selinux /proc/mounts|cut -d " " -f 2`
-	[ -n sedir ] && {
-		se_enforce=`cat $sedir/enforce`
-		if [ "$se_enforce" -ge 1 ]; then
-			echo 0 > $sedir/enforce 2>&1 > /dev/null
-		fi
-	}
-
 	while read config_opt config_val; do
 		case "$config_opt" in
 		sshkey)
@@ -416,11 +453,6 @@ function propagate_ssh_key()
 		echo "done."
 	fi
 
-	#If necessary, flip selinux back to enforcing
-	if [ "$se_enforce" -ge 1 ]; then
-		echo 1 > $sedir/enforce 2>&1 > /dev/null
-	fi
-	
 	#now find the target ssh user and server to contact.
 	SSH_USER=`echo $SSH_TARGET | cut -d\  -f2 | cut -d@ -f1`
 	SSH_SERVER=`echo $SSH_TARGET | sed -e's/\(.*@\)\(.*$\)/\2/'`
@@ -494,6 +526,76 @@ function save_raw()
 	return 0
 }
 
+get_save_path() {
+	local _save_path=$(grep "^path" /etc/kdump.conf|awk '{print $2}')
+	if [ -z "$_save_path" ]; then
+		_save_path="/var/crash"
+	fi
+
+	echo $_save_path
+}
+
+is_dump_target_configured() {
+    local _target
+
+    _target=$(egrep "^ext[234]|^xfs|^btrfs|^minix|^raw|^ssh|^nfs|^nfs4|^net" /etc/kdump.conf)
+
+     [ -n "$_target" ]
+}
+
+local_fs_dump_target()
+{
+	local _target
+
+	_target=$(egrep "^ext[234]|^xfs|^btrfs|^minix" /etc/kdump.conf)
+	if [ $? -eq 0 ]; then
+		echo $_target|awk '{print $2}'
+	fi
+}
+
+path_to_be_relabeled() {
+	local _path _target _mnt="/" _rmnt
+
+	if is_dump_target_configured; then
+		_target=$(local_fs_dump_target)
+		if [[ -n "$_target" ]]; then
+			_mnt=$(findmnt -k -f -n -r -o TARGET $_target)
+			if [ -z "$_mnt" ]; then
+				return
+			fi
+		else
+			return
+		fi
+	fi
+
+	_path=$(get_save_path)
+	# if $_path is masked by other mount, we will not relabel it.
+	# one exception is ! is_dump_target_configure && "$_rmnt" != "$_mnt"
+	# for this exception see mkdumprd code about [ -z "$USING_METHOD" ]
+	_rmnt=$(df $_mnt/$_path 2>/dev/null | tail -1 | awk '{ print $NF }')
+	if [[ "$_rmnt" == "$_mnt" ]] || ! is_dump_target_configured; then
+		echo $_mnt/$_path
+	fi
+}
+
+selinux_relabel()
+{
+	local _path _i _attr
+
+	_path=$(path_to_be_relabeled)
+	if [ -z "$_path" ] || ! [ -d "$_path" ] ; then
+		return
+	fi
+
+	for _i in $(find $_path); do
+		_attr=$(getfattr -m "security.selinux" $_i 2>/dev/null)
+		if [ -z "$_attr" ]; then
+			restorecon $_i;
+		fi
+	done
+}
+
+
 # Notes about xen support:
 # pv guests are not supported
 # hvm guests are supported only when you ensure below items:
@@ -503,6 +605,9 @@ function save_raw()
 #    are not loaded
 function start()
 {
+	if sestatus 2>/dev/null | grep -q "SELinux status.*enabled"; then
+		selinux_relabel
+	fi
 	save_raw
 	if [ $? -ne 0 ]; then
 		echo -n "Starting kdump:"; failure; echo
@@ -560,6 +665,9 @@ function stop()
 		return 1
 	fi
 }
+
+# Other kdump init instances will block in queue, until this one exits.
+single_instance_lock
 
 case "$1" in
   start)
diff --git a/rc.d/init.d/mysqld b/rc.d/init.d/mysqld
--- a/rc.d/init.d/mysqld
+++ b/rc.d/init.d/mysqld
@@ -8,6 +8,13 @@
 # processname: mysqld
 # config: /etc/my.cnf
 # pidfile: /var/run/mysqld/mysqld.pid
+### BEGIN INIT INFO
+# Provides: mysqld
+# Required-Start: $local_fs $remote_fs $network $named $syslog $time
+# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
+# Short-Description: start and stop MySQL server
+# Description: MySQL database server
+### END INIT INFO
 
 # Source function library.
 . /etc/rc.d/init.d/functions
@@ -54,19 +61,31 @@ mypidfile="$result"
 start(){
     [ -x $exec ] || exit 5
     # check to see if it's already running
+    MYSQLDRUNNING=0
+    if [ -f "$mypidfile" ]; then
+	MYSQLPID=`cat "$mypidfile" 2>/dev/null`
+	if [ -n "$MYSQLPID" ] && [ -d "/proc/$MYSQLPID" ] ; then
+	    MYSQLDRUNNING=1
+	fi
+    fi
     RESPONSE=`/usr/bin/mysqladmin --socket="$socketfile" --user=UNKNOWN_MYSQL_USER ping 2>&1`
-    if [ $? = 0 ]; then
+    if [ $MYSQLDRUNNING = 1 ] && [ $? = 0 ]; then
 	# already running, do nothing
 	action $"Starting $prog: " /bin/true
 	ret=0
-    elif echo "$RESPONSE" | grep -q "Access denied for user"
+    elif [ $MYSQLDRUNNING = 1 ] && echo "$RESPONSE" | grep -q "Access denied for user"
     then
 	# already running, do nothing
 	action $"Starting $prog: " /bin/true
 	ret=0
     else
     	# prepare for start
-	touch "$errlogfile"
+	touch "$errlogfile" 2>/dev/null
+	if [ $? -ne 0 ]; then
+	     # failed to touch log file, probably insufficient permissions
+	    action $"Starting $prog: " /bin/false
+	    return 4
+	fi
 	chown mysql:mysql "$errlogfile" 
 	chmod 0640 "$errlogfile"
 	[ -x /sbin/restorecon ] && /sbin/restorecon "$errlogfile"
@@ -89,6 +108,15 @@ start(){
 	fi
 	chown mysql:mysql "$datadir"
 	chmod 0755 "$datadir"
+	# We check if there is already a process using the socket file,
+	# since otherwise this init script could report false positive
+	# result and mysqld_safe would remove the socket file, which
+	# actually uses a different daemon.
+	if fuser "$socketfile" &>/dev/null ; then
+	    echo "Socket file $socketfile exists. Is another MySQL daemon already running with the same unix socket?"
+	    action $"Starting $prog: " /bin/false
+	    return 1
+	fi
 	# Pass all the options determined above, to ensure consistent behavior.
 	# In many cases mysqld_safe would arrive at the same conclusions anyway
 	# but we need to be sure.  (An exception is that we don't force the
@@ -107,7 +135,19 @@ start(){
 	ret=0
 	TIMEOUT="$STARTTIMEOUT"
 	while [ $TIMEOUT -gt 0 ]; do
-	    RESPONSE=`/usr/bin/mysqladmin --socket="$socketfile" --user=UNKNOWN_MYSQL_USER ping 2>&1` && break
+	    RESPONSE=`/usr/bin/mysqladmin --socket="$socketfile" --user=UNKNOWN_MYSQL_USER ping 2>&1`
+	    mret=$?
+	    if [ $mret -eq 0 ]; then
+		break
+	    fi
+	    # exit codes 1, 11 (EXIT_CANNOT_CONNECT_TO_SERVICE) are expected,
+	    # anything else suggests a configuration error
+	    if [ $mret -ne 1 -a $mret -ne 11 ]; then
+		echo "$RESPONSE"
+		echo "Cannot check for MySQL Daemon startup because of mysqladmin failure."
+		ret=1
+		break
+	    fi
 	    echo "$RESPONSE" | grep -q "Access denied for user" && break
 	    if ! /bin/kill -0 $safe_pid 2>/dev/null; then
 		echo "MySQL Daemon failed to start."
@@ -123,6 +163,7 @@ start(){
 	fi
 	if [ $ret -eq 0 ]; then
 	    action $"Starting $prog: " /bin/true
+	    chmod o+r $mypidfile >/dev/null 2>&1
 	    touch $lockfile
 	else
 	    action $"Starting $prog: " /bin/false
@@ -137,7 +178,7 @@ stop(){
 	    action $"Stopping $prog: " /bin/true
 	    return 0
 	fi
-	MYSQLPID=`cat "$mypidfile"`
+	MYSQLPID=`cat "$mypidfile" 2>/dev/null`
 	if [ -n "$MYSQLPID" ]; then
 	    /bin/kill "$MYSQLPID" >/dev/null 2>&1
 	    ret=$?
diff --git a/sysconfig/network-scripts/ifup-eth b/sysconfig/network-scripts/ifup-eth
--- a/sysconfig/network-scripts/ifup-eth
+++ b/sysconfig/network-scripts/ifup-eth
@@ -61,6 +61,12 @@ if [ "${TYPE}" = "Bridge" ]; then
       fi
       [ -n "${DELAY}" ] && /usr/sbin/brctl setfd ${DEVICE} ${DELAY}
       [ -n "${STP}" ] && /usr/sbin/brctl stp ${DEVICE} ${STP}
+      # add the bits to setup driver parameters here
+      for arg in $BRIDGING_OPTS ; do
+          key=${arg%%=*};
+          value=${arg##*=};
+          echo $value > /sys/class/net/${DEVICE}/bridge/$key
+      done
 fi
 
 # If the device is a tap device, create it with tunctl, if available.
@@ -112,37 +118,14 @@ fi
 # Bonding initialization. For DHCP, we need to enslave the devices early,
 # so it can actually get an IP.
 if [ "$ISALIAS" = no ] && is_bonding_device ${DEVICE} ; then
-
-    /sbin/ip link set dev ${DEVICE} down
-
-    # add the bits to setup driver parameters here
-    for arg in $BONDING_OPTS ; do   
-        key=${arg%%=*};
-        value=${arg##*=};
-        if [ "${key}" = "arp_ip_target" -a "${value:0:1}" != "+" ]; then
-            OLDIFS=$IFS;
-            IFS=',';
-            for arp_ip in $value; do
-		if ! grep -q $arp_ip /sys/class/net/${DEVICE}/bonding/$key; then
-                    echo +$arp_ip > /sys/class/net/${DEVICE}/bonding/$key
-		fi
-            done
-            IFS=$OLDIFS;
-        elif [ "${key}" = "arp_ip_target" ]; then
-	    if ! grep -q ${value#+} /sys/class/net/${DEVICE}/bonding/$key; then
-                echo "$value" > /sys/class/net/${DEVICE}/bonding/$key
-	    fi
-	elif [ "${key}" != "primary" ]; then
-            echo $value > /sys/class/net/${DEVICE}/bonding/$key
-        fi
-    done
-
+    install_bonding_driver ${DEVICE}
     /sbin/ip link set dev ${DEVICE} up
-    [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
-    for device in $(LANG=C egrep -l "^[[:space:]]*MASTER=\"?${DEVICE}\"?" /etc/sysconfig/network-scripts/ifcfg-*) ; do
+    for device in $(LANG=C grep -l "^[[:space:]]*MASTER=\"\?${DEVICE}\"\?\([[:space:]#]\|$\)" /etc/sysconfig/network-scripts/ifcfg-*) ; do
 	    is_ignored_file "$device" && continue
 	    /sbin/ifup ${device##*/}
     done
+
+    [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
 
     # add the bits to setup the needed post enslavement parameters
     for arg in $BONDING_OPTS ; do   
@@ -164,6 +147,12 @@ if [ -n "${BRIDGE}" -a -x /usr/sbin/brctl ]; then
       ethtool_set
       [ -n "${LINKDELAY}" ] && /bin/sleep ${LINKDELAY}
       /usr/sbin/brctl addif ${BRIDGE} ${DEVICE}
+      # add the bits to setup driver parameters here
+      for arg in $BRIDGING_OPTS ; do
+          key=${arg%%=*};
+          value=${arg##*=};
+          echo $value > /sys/class/net/${DEVICE}/brport/$key
+      done
       # Upon adding a device to a bridge,
       # it's necessary to make radvd reload its config
       [ -r /var/run/radvd/radvd.pid ] && kill -HUP $(cat /var/run/radvd/radvd.pid)
@@ -176,15 +165,7 @@ if [ -n "${DYNCONFIG}" -a -x /sbin/dhclient ]; then
     else
        ONESHOT="-1";
     fi;
-    # allow users to use generic '/etc/dhclient.conf' (as documented in manpage!) 
-    # if per-device file doesn't exist or is empty
-    if [ -s /etc/dhcp/dhclient-${DEVICE}.conf ]; then
-       DHCLIENTCONF="-cf /etc/dhcp/dhclient-${DEVICE}.conf";
-    elif [ -s /etc/dhclient-${DEVICE}.conf ]; then
-       DHCLIENTCONF="-cf /etc/dhclient-${DEVICE}.conf";
-    else
-       DHCLIENTCONF='';
-    fi;
+    generate_config_file_name
     # copy any lease obtained by the initrd
     for file in /dev/.dhclient-${DEVICE}.leases /dev/.initramfs/net.${DEVICE}.lease ; do
         if [ -f "${file}" ]; then
@@ -203,10 +184,17 @@ if [ -n "${DYNCONFIG}" -a -x /sbin/dhclient ]; then
     ethtool_set
 
     if /sbin/dhclient ${DHCLIENTARGS} ${DEVICE} ; then
-	echo $" done."
+		echo $" done."
+		dhcpipv4="good"
     else
-	echo $" failed."
-	exit 1
+		echo $" failed."
+		if [[ "${IPV4_FAILURE_FATAL}"  = [Yy1]* ]] ; then
+			exit 1
+		fi
+		if [[ "$IPV6INIT" != [yY1]* && "$DHCPV6C" != [yY1]* ]] ; then
+			exit 1
+		fi
+		net_log "Unable to obtain IPv4 DHCP address ${DEVICE}." warning
     fi
 # end dynamic device configuration
 else 
@@ -250,11 +238,13 @@ else
         fi
 
         if ! LC_ALL=C ip addr ls ${REALDEVICE} | LC_ALL=C grep -q "${ipaddr[$idx]}/${prefix[$idx]}" ; then
-            [ "${REALDEVICE}" != "lo" ] && \
-            if ! /sbin/arping -q -c 2 -w 3 -D -I ${REALDEVICE} ${ipaddr[$idx]} ; then
-                net_log $"Error, some other host already uses address ${ipaddr[$idx]}."
-                exit 1
-            fi
+            if [ "${REALDEVICE}" != "lo" ] && [ "${arpcheck[$idx]}" != "no" ] ; then
+				echo $"Determining if ip address ${ipaddr[$idx]} is already in use for device ${REALDEVICE}..."
+				if ! /sbin/arping -q -c 2 -w 3 -D -I ${REALDEVICE} ${ipaddr[$idx]} ; then
+					net_log $"Error, some other host already uses address ${ipaddr[$idx]}."
+					exit 1
+				fi
+			fi
 
             if ! ip addr add ${ipaddr[$idx]}/${prefix[$idx]} \
               brd ${broadcast[$idx]:-+} dev ${REALDEVICE} ${SCOPE} label ${DEVICE}; then
@@ -299,7 +289,23 @@ fi
 # IPv6 initialisation?
 /etc/sysconfig/network-scripts/ifup-ipv6 ${CONFIG}
 if [[ "${DHCPV6C}"  = [Yy1]* ]] && [ -x /sbin/dhclient ]; then
-    /sbin/dhclient -6 -1 ${DHCPV6C_OPTIONS} -lf /var/lib/dhclient/dhclient6-${DEVICE}.leases -pf /var/run/dhclient6-${DEVICE}.pid ${DHCP_HOSTNAME:+-H $DHCP_HOSTNAME} ${DEVICE}
+    generate_config_file_name 6
+    echo
+    echo -n $"Determining IPv6 information for ${DEVICE}..."
+    if /sbin/dhclient -6 -1 ${DHCPV6C_OPTIONS} ${DHCLIENTCONF} -lf /var/lib/dhclient/dhclient6-${DEVICE}.leases -pf /var/run/dhclient6-${DEVICE}.pid ${DHCP_HOSTNAME:+-H $DHCP_HOSTNAME} ${DEVICE} ; then
+        echo $" done."
+    else
+        echo $" failed."
+        if [ "${dhcpipv4}" = "good" -o -n "${IPADDR}" ]; then
+            net_log "Unable to obtain IPv6 DHCP address ${DEVICE}." warning
+        else
+            exit 1
+        fi
+    fi
+fi
+
+if [ "${IPX}" = yes ]; then
+       /etc/sysconfig/network-scripts/ifup-ipx ${DEVICE}
 fi
 
 exec /etc/sysconfig/network-scripts/ifup-post ${CONFIG} ${2}
